1 fase - Etapas importantes:
Ler todas as colunas
Identificar variáveis importantes
Criar um mini dicionário de dados

2 fase - Etapas importantes:
Ver quantas linhas e colunas existem
Ver quais colunas têm valores faltantes
Ver estatísticas básicas
Ver quais são as classes de solo existentes
Plotar gráficos simples

3 fase - etapas importantes:
Entender a Lógica do Solo

4 fase -Etapas importantes:
Criar Gráficos e Descobrir Padrões

# Importação dataset csv do Drive para Colab

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

file_path = '/content/drive/MyDrive/amazonia/Amazonia/PedologiaAmazoniaLegal_250.csv'
df = pd.read_csv(file_path)
display(df.head())

,FID,Folha,Unidade_Mapeamento,Quantidade_Componentes,Solo_ou_Terreno,Simbolo_Unidade,Ordem,Subordem,Grande_Grupo,Subgrupo,Descricao,Inclusoes,Textura_Principal_Componente,Horizonte_Principal_Componente,Erosao_Principal_Componente,Pedregosidade_Principal_Componente,Rochosidade_Principal_Componente,Relevo_Principal_Componente,Area_Poligono_Km2,the_geom
0,PedologiaAmazoniaLegal_250.fid--53d9e96d_19abb...,NA19,AR6,2,AR - Afloramentos De Rochas,AR,AFLORAMENTOS DE ROCHAS,NaN,NaN,NaN,"AFLORAMENTOS DE ROCHAS ondulado, forte ondulad...",NaN,NaN,NaN,NaN,NaN,NaN,"ondulado, forte ondulado, montanhoso e escarpado",11.335,MULTIPOLYGON (((-68.14755541058953 1.473460296...
1,PedologiaAmazoniaLegal_250.fid--53d9e96d_19abb...,NA19,AR14,3,AR - Afloramentos De Rochas,AR,AFLORAMENTOS DE ROCHAS,NaN,NaN,NaN,AFLORAMENTOS DE ROCHAS forte ondulado\r\n NEOS...,NaN,NaN,NaN,NaN,NaN,NaN,forte ondulado,46.073,MULTIPOLYGON (((-66.0319793361047 0.8116576254...
2,PedologiaAmazoniaLegal_250.fid--53d9e96d_19abb...,NA19,AR14,3,AR - Afloramentos De Rochas,AR,AFLORAMENTOS DE ROCHAS,NaN,NaN,NaN,AFLORAMENTOS DE ROCHAS forte ondulado\r\n NEOS...,NaN,NaN,NaN,NaN,NaN,NaN,forte ondulado,55.707,MULTIPOLYGON (((-68.16683458136062 1.984870043...
3,PedologiaAmazoniaLegal_250.fid--53d9e96d_19abb...,NA19,AR14,3,AR - Afloramentos De Rochas,AR,AFLORAMENTOS DE ROCHAS,NaN,NaN,NaN,AFLORAMENTOS DE ROCHAS forte ondulado\r\n NEOS...,NaN,NaN,NaN,NaN,NaN,NaN,forte ondulado,5.281,MULTIPOLYGON (((-67.91137052643609 1.814806420...
4,PedologiaAmazoniaLegal_250.fid--53d9e96d_19abb...,NA19,PAa1,2,PAa - Argissolo Amarelo Alumínico,PAa,ARGISSOLO,AMARELO,Alumínico,abrúptico,ARGISSOLO AMARELO Alumínico abrúptico arenosa/...,CAMBISSOLO HÁPLICO Alumínico típico argilosa A...,arenosa/média,A moderado,NaN,NaN,NaN,plano e suave ondulado,41.742,MULTIPOLYGON (((-66.00082267276014 0.062594019...

#Entendimento do negocio

Criar Dicionario de Dados

#Entendimento dos dados

In [9]:
import pandas as pd

dicionario = pd.DataFrame({
    "Coluna": [
        "FID",
        "Folha",
        "Unidade_Mapeamento",
        "Quantidade_Componentes",
        "Solo_ou_Terreno",
        "Simbolo_Unidade",
        "Ordem",
        "Subordem",
        "Grande_Grupo",
        "Subgrupo",
        "Descricao",
        "Inclusoes",
        "Textura_Principal_Componente",
        "Horizonte_Principal_Componente",
        "Erosao_Principal_Componente",
        "Pedregosidade_Principal_Componente",
        "Rochosidade_Principal_Componente",
        "Relevo_Principal_Componente",
        "Area_Poligono_Km2",
        "the_geom"
    ],
    "Tipo": [
        "int64",
        "object",
        "object",
        "int64",
        "object",
        "object",
        "object",
        "object",
        "object",
        "object",
        "object",
        "object",
        "object",
        "object",
        "object",
        "object",
        "object",
        "object",
        "float64",
        "object"
    ],
    "Descricao": [
        "Identificador único do registro",
        "Código da folha cartográfica (mapa) correspondente",
        "Código da unidade de mapeamento do solo",
        "Número de componentes presentes na unidade mapeada",
        "Nome geral do solo ou terreno descrito",
        "Símbolo cartográfico da unidade de solo",
        "Ordem taxonômica do solo (nível mais amplo: ex. Latossolo, Argissolo)",
        "Subordem dentro da ordem taxonômica",
        "Grande grupo taxonômico (nível intermediário)",
        "Subgrupo taxonômico (nível mais detalhado)",
        "Descrição completa do tipo e características do solo",
        "Presença de inclusões (solos secundários dentro da unidade principal)",
        "Textura principal (argilosa, arenosa, siltosa etc.)",
        "Horizonte principal (A, B, C – profundidade e estrutura do solo)",
        "Grau de erosão identificado no componente principal",
        "Nível de pedregosidade (presença de pedras/cascalho)",
        "Rochosidade da área (presença de afloramentos rochosos)",
        "Tipo de relevo (plano, ondulado, montanhoso, etc.)",
        "Área do polígono em km² representando a unidade de solo",
        "Geometria do polígono ou ponto em formato WKT"
    ]
})
print(dicionario)

                                Coluna     Tipo  \
0                                  FID    int64
1                                Folha   object
2                   Unidade_Mapeamento   object
3               Quantidade_Componentes    int64
4                      Solo_ou_Terreno   object
5                      Simbolo_Unidade   object
6                                Ordem   object
7                             Subordem   object
8                         Grande_Grupo   object
9                             Subgrupo   object
10                           Descricao   object
11                           Inclusoes   object
12        Textura_Principal_Componente   object
13      Horizonte_Principal_Componente   object
14         Erosao_Principal_Componente   object
15  Pedregosidade_Principal_Componente   object
16    Rochosidade_Principal_Componente   object
17         Relevo_Principal_Componente   object
18                   Area_Poligono_Km2  float64
19                            the_geom   object

                                            Descricao
0                     Identificador único do registro
1   Código da folha cartográfica (mapa) correspond...
2             Código da unidade de mapeamento do solo
3   Número de componentes presentes na unidade map...
4              Nome geral do solo ou terreno descrito
5             Símbolo cartográfico da unidade de solo
6   Ordem taxonômica do solo (nível mais amplo: ex...
7                 Subordem dentro da ordem taxonômica
8       Grande grupo taxonômico (nível intermediário)
9          Subgrupo taxonômico (nível mais detalhado)
10  Descrição completa do tipo e características d...
11  Presença de inclusões (solos secundários dentr...
12  Textura principal (argilosa, arenosa, siltosa ...
13  Horizonte principal (A, B, C – profundidade e ...
14  Grau de erosão identificado no componente prin...
15  Nível de pedregosidade (presença de pedras/cas...
16  Rochosidade da área (presença de afloramentos ...
17  Tipo de relevo (plano, ondulado, montanhoso, e...
18  Área do polígono em km² representando a unidad...
19      Geometria do polígono ou ponto em formato WKT

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62495 entries, 0 to 62494
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   FID                                 62495 non-null  object
 1   Folha                               62495 non-null  object
 2   Unidade_Mapeamento                  62495 non-null  object
 3   Quantidade_Componentes              62495 non-null  int64
 4   Solo_ou_Terreno                     62495 non-null  object
 5   Simbolo_Unidade                     62495 non-null  object
 6   Ordem                               40691 non-null  object
 7   Subordem                            40323 non-null  object
 8   Grande_Grupo                        40323 non-null  object
 9   Subgrupo                            40323 non-null  object
 10  Descricao                           40691 non-null  object
 11  Inclusoes                           19232 non-null  object
 12  Textura_Principal_Componente        40323 non-null  object
 13  Horizonte_Principal_Componente      40323 non-null  object
 14  Erosao_Principal_Componente         348 non-null    object
 15  Pedregosidade_Principal_Componente  1305 non-null   object
 16  Rochosidade_Principal_Componente    584 non-null    object
 17  Relevo_Principal_Componente         40687 non-null  object
 18  Area_Poligono_Km2                   62495 non-null  float64
 19  the_geom                            62495 non-null  object
dtypes: float64(1), int64(1), object(18)
memory usage: 9.5+ MB

In [4]:
df.describe()

       Quantidade_Componentes  Area_Poligono_Km2
count            62495.000000       62495.000000
mean                 1.661381          80.135319
std                  1.374426         516.927624
min                  0.000000           0.004000
25%                  0.000000           0.144000
50%                  2.000000           1.498000
75%                  3.000000          19.411500
max                  7.000000       59714.359000

In [6]:
df.head()

,FID,Folha,Unidade_Mapeamento,Quantidade_Componentes,Solo_ou_Terreno,Simbolo_Unidade,Ordem,Subordem,Grande_Grupo,Subgrupo,Descricao,Inclusoes,Textura_Principal_Componente,Horizonte_Principal_Componente,Erosao_Principal_Componente,Pedregosidade_Principal_Componente,Rochosidade_Principal_Componente,Relevo_Principal_Componente,Area_Poligono_Km2,the_geom
0,PedologiaAmazoniaLegal_250.fid--53d9e96d_19abb...,NA19,AR6,2,AR - Afloramentos De Rochas,AR,AFLORAMENTOS DE ROCHAS,NaN,NaN,NaN,"AFLORAMENTOS DE ROCHAS ondulado, forte ondulad...",NaN,NaN,NaN,NaN,NaN,NaN,"ondulado, forte ondulado, montanhoso e escarpado",11.335,MULTIPOLYGON (((-68.14755541058953 1.473460296...
1,PedologiaAmazoniaLegal_250.fid--53d9e96d_19abb...,NA19,AR14,3,AR - Afloramentos De Rochas,AR,AFLORAMENTOS DE ROCHAS,NaN,NaN,NaN,AFLORAMENTOS DE ROCHAS forte ondulado\r\n NEOS...,NaN,NaN,NaN,NaN,NaN,NaN,forte ondulado,46.073,MULTIPOLYGON (((-66.0319793361047 0.8116576254...
2,PedologiaAmazoniaLegal_250.fid--53d9e96d_19abb...,NA19,AR14,3,AR - Afloramentos De Rochas,AR,AFLORAMENTOS DE ROCHAS,NaN,NaN,NaN,AFLORAMENTOS DE ROCHAS forte ondulado\r\n NEOS...,NaN,NaN,NaN,NaN,NaN,NaN,forte ondulado,55.707,MULTIPOLYGON (((-68.16683458136062 1.984870043...
3,PedologiaAmazoniaLegal_250.fid--53d9e96d_19abb...,NA19,AR14,3,AR - Afloramentos De Rochas,AR,AFLORAMENTOS DE ROCHAS,NaN,NaN,NaN,AFLORAMENTOS DE ROCHAS forte ondulado\r\n NEOS...,NaN,NaN,NaN,NaN,NaN,NaN,forte ondulado,5.281,MULTIPOLYGON (((-67.91137052643609 1.814806420...
4,PedologiaAmazoniaLegal_250.fid--53d9e96d_19abb...,NA19,PAa1,2,PAa - Argissolo Amarelo Alumínico,PAa,ARGISSOLO,AMARELO,Alumínico,abrúptico,ARGISSOLO AMARELO Alumínico abrúptico arenosa/...,CAMBISSOLO HÁPLICO Alumínico típico argilosa A...,arenosa/média,A moderado,NaN,NaN,NaN,plano e suave ondulado,41.742,MULTIPOLYGON (((-66.00082267276014 0.062594019...

In [8]:
df.isnull().sum()

FID                                       0
Folha                                     0
Unidade_Mapeamento                        0
Quantidade_Componentes                    0
Solo_ou_Terreno                           0
Simbolo_Unidade                           0
Ordem                                 21804
Subordem                              22172
Grande_Grupo                          22172
Subgrupo                              22172
Descricao                             21804
Inclusoes                             43263
Textura_Principal_Componente          22172
Horizonte_Principal_Componente        22172
Erosao_Principal_Componente           62147
Pedregosidade_Principal_Componente    61190
Rochosidade_Principal_Componente      61911
Relevo_Principal_Componente           21808
Area_Poligono_Km2                         0
the_geom                                  0
dtype: int64

#Preparação dos dados

#Modelagem

# Avaliação

#Implantação