In [8]:
import pandas as pd

In [3]:
dados ={
    "Nome":["Jetta","Passat", "Crossfox","DS5","Fusca"],
    "Motor":["Motor 4.0 Turbo", "Motor Diesel", "Motor Diesel V8", "Motor 2.0", "Motor 1.6"],
    "Ano":[2019,2003,1991,2019,1990],
    "Quilometragem":[0.0,5712.0,37123.0,0.0,120000.0],
    "Valor":[88000.0,106000.0,72000.0,89000.0,32000.0],
    "IPVA":[2000.0,5000.0,1700.0,2200.0,1000.0],
    "Desconto":[380.0,450.0,277.0,400.0,150.0]
}

In [9]:
dataframe = pd.DataFrame(dados)
dataframe

       Nome            Motor   Ano  Quilometragem     Valor    IPVA  Desconto
0     Jetta  Motor 4.0 Turbo  2019            0.0   88000.0  2000.0     380.0
1    Passat     Motor Diesel  2003         5712.0  106000.0  5000.0     450.0
2  Crossfox  Motor Diesel V8  1991        37123.0   72000.0  1700.0     277.0
3       DS5        Motor 2.0  2019            0.0   89000.0  2200.0     400.0
4     Fusca        Motor 1.6  1990       120000.0   32000.0  1000.0     150.0

In [10]:
dataframe["Valor_total"] = dataframe["Valor"] + dataframe["IPVA"]- dataframe["Desconto"]

In [11]:
dataframe

,Nome,Motor,Ano,Quilometragem,Valor,IPVA,Desconto,Valor_total
0,Jetta,Motor 4.0 Turbo,2019,0.0,88000.0,2000.0,380.0,89620.0
1,Passat,Motor Diesel,2003,5712.0,106000.0,5000.0,450.0,110550.0
2,Crossfox,Motor Diesel V8,1991,37123.0,72000.0,1700.0,277.0,73423.0
3,DS5,Motor 2.0,2019,0.0,89000.0,2200.0,400.0,90800.0
4,Fusca,Motor 1.6,1990,120000.0,32000.0,1000.0,150.0,32850.0