In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/serenatto_2sem_2023.csv')

In [ ]:
df.head()

     id        data           produto  valor   metodo_pagamento
0  2720  2023-07-01  Risoto de Funghi   13.0   Cartão de Débito
1  2721  2023-07-02          Tiramisù   10.0   Cartão de Débito
2  2722  2023-07-02          Tiramisù   10.0  Cartão de Crédito
3  2723  2023-07-02       Ratatouille    8.5                PIX
4  2724  2023-07-03       Ratatouille    8.5           Dinheiro

In [ ]:
df.shape

(856, 5)

In [ ]:
df[df['produto']=='Ratatouille'].sum()

id                                                             119914
data                2023-07-022023-07-032023-07-062023-07-102023-0...
produto             RatatouilleRatatouilleRatatouilleRatatouilleRa...
valor                                                           323.0
metodo_pagamento    PIXDinheiroPIXCartão de CréditoPIXDinheiroPIXC...
dtype: object

In [ ]:
valor_total_arrecadado = df.query('produto =="Ratatouille"').valor.sum()

In [ ]:
frequencia_metodo_pagamento = df.query('produto == "Ratatouille"').metodo_pagamento.value_counts()

In [ ]:
df.query('valor > 10 and metodo_pagamento != "Dinheiro" and produto=="Lasanha"').metodo_pagamento.value_counts()

metodo_pagamento
PIX                  13
Cartão de Crédito    12
Cartão de Débito      6
Name: count, dtype: int64